package com.kartuku.digitalwallet.common;

public class Constants
{
  public static final String ACCESSTOKEN_KEY = "SECURITY-TOKEN";
  public static final String ADD_SUCCESS = "Add Success";
  public static final String AUTH_CAPTURE_SUCCESS = "Auth Capture Success";
  public static final String BALANCE_KEY = "balance";
  public static final String BILLPAY_ADVICE = "BILL-PAYMENT PRODUCT ADVICE INQ";
  public static final String BILLPAY_LIST_PRICE = "BILL-PAYMENT LIST PRICE INQ";
  public static final String BILLPAY_LIST_PRODUCT = "BILL-PAYMENT LIST PRODUCT INQ";
  public static final String BILLPAY_PURCHASE = "BILL-PAYMENT PRODUCT PURCHASE REQ";
  public static final String BLOCK_CARD = "BLOCK CARD";
  public static final String BLOCK_CARD_FAILED = "Block Card Failed";
  public static final String BLOCK_CARD_STATUS_BLOCKED = "Card Blocked";
  public static final String BLOCK_CARD_SUCCESS = "Block Card Success";
  public static final String CANCEL_TOP_UP_PREPAID = "CANCEL TOP UP PREPAID";
  public static final String CARDLINKID_KEY = "CARDLINKID";
  public static final String CARDLINK_UID_KEY = "cardLinkUserId";
  public static final String CARDVOUCHER_LIST_KEY = "cardVoucherList";
  public static final String CARD_LIST = "GET CARD LIST";
  public static final String CC_PREPAID_TYPE = "O";
  public static final String CHANGE_PASSWORD_USER = "CHANGE PASSWORD USER";
  public static final String CHECK_SESSION = "/checkSession";
  public static final String CODE_KEY = "code";
  public static final String COMPANYCODE_KEY = "Company-Code";
  public static final String CONF_OTP_USER_DEVICE_IMPRINTS = "CONFIRM USER DEVICE IMPRINTS";
  public static final String CONTEXT_ID_KEY = "CONTEXTID";
  public static final String CREDIT_CARD_PURCHASE = "CREDIT CARD PURCHASE";
  public static final String CREDIT_PURCHASE_HISTORY = "CREDIT PURCHASE HISTORY";
  public static final String DATA_EXIST = "Data Exist";
  public static final String DATA_FLAG = "Member List";
  public static final String DEFAULT_FAIL = "FAIL";
  public static final Integer DEFAULT_PASWD_LENGTH = Integer.valueOf(8);
  public static final String DEFAULT_SUCCESS = "OK";
  public static final Integer DELETED;
  public static final String DELETE_SUCCESS = "Delete Success";
  public static final String DELETE_USER = "DELETE USER";
  public static final String DETAIL_KEY = "detail";
  public static final Integer DISABLE;
  public static final String EMPTY_STRING = "";
  public static final Integer ENABLE = Integer.valueOf(1);
  public static final Long ERROR_INDEX;
  public static final String ERROR_MESSAGE = "FAIL";
  public static final String ERROR_MESSAGE_BULK = "File not compatible";
  public static final String ERROR_NOT_FOUND = "Data not found";
  public static final String FAILED = "Failed";
  public static final String FAIL_ADD_CONFIG = "Add Config Failed";
  public static final String FAIL_AUTHORIZE = "Authorize failed";
  public static final String FAIL_CAPTURE = "Capture failed";
  public static final String FAIL_CONFIG_NOT_FOUND = "User Config Not Found";
  public static final String FAIL_GENERATE_NEW_CARD = "Failed request to make a new card";
  public static final String FAIL_MESSAGE_TOPUP = "Top Up Card Failed";
  public static final String FAIL_RETRIEVE_DETAIL_OR_UNTOKEN = "Retrieve Card Detail or Untoken Failed";
  public static final String FAIL_SAVE_TO_DB = "Failed to Save New User Into Database, make sure you have a unique uid";
  public static final String FAIL_SEND_NOTIFICATION = "Failed to send notification";
  public static final String FAIL_STATUS_CODE = "0";
  public static final String FAIL_STATUS_CODE_CARD_DETAIL = "44";
  public static final String FAIL_STATUS_CODE_CONFIG = "48";
  public static final String FAIL_STATUS_CODE_KTS_RETRIEVE = "45";
  public static final String FAIL_STATUS_CODE_LINK = "42";
  public static final String FAIL_STATUS_CODE_LOGOUT = "47";
  public static final String FAIL_STATUS_CODE_NOT_FOUND = "41";
  public static final String FAIL_STATUS_CODE_SERVER_ERROR = "46";
  public static final String FAIL_STATUS_CODE_TOPUP = "43";
  public static final String FAIL_STATUS_IPG_REQUEST = "50";
  public static final String FAIL_STATUS_NOTIFICATION = "49";
  public static final String FAIL_UPDATE_CONFIG = "Update Config Failed";
  public static final String FIND_SUCCESS = "Data found";
  public static final String FIND_USER = "FIND USER";
  public static final String FORGOT_PASSWORD_USER = "FORGOT PASSWORD USER";
  public static final String FORGOT_PWD_PATH = "/user/forgotpwd";
  public static final Integer GENERIC_SERVICE_CARDLINK;
  public static final Integer GENERIC_SERVICE_IAM;
  public static final Integer GENERIC_SERVICE_PREPAID = Integer.valueOf(4);
  public static final Integer GENERIC_SERVICE_PROMO;
  public static final String GET_USER_CONFIG = "GET USER CONFIG";
  public static final String GIFTCARD_BALANCE = "GET CARD HISTORY";
  public static final String GIFTCARD_DETAIL = "GET CARD DETAIL";
  public static final String GIFTCARD_HISTORY = "GET CARD HISTORY";
  public static final String IAM_CREDENTIAL_KEY = "IAM_CREDENTIAL";
  public static final String IAM_GENERIC = "IAM";
  public static final String IAM_RESPONSE_DATA_EXIST_MESSAGE = "ERROR: duplicate key";
  public static final String IAM_SERVER_REQUEST = "IAM-SERVER";
  public static final String IAM_USER_REQUEST = "IAM-USER";
  public static final String ID_KEY = "id";
  public static final String INQUIRY_COUPON = "INQUIRY COUPON";
  public static final String INQUIRY_CREDIT = "INQUIRY CREDIT";
  public static final String INQUIRY_POINT = "INQUIRY POINT";
  public static final String IPG_AUTHORIZE = "IPG AUTHORIZE";
  public static final String IPG_AUTH_CAPTURE = "IPG AUTH AND CAPTURE";
  public static final String IPG_CAPTURE = "IPG CAPTURE";
  public static final String IPG_OTT = "IPG OTT";
  public static final String IPG_OTT_PURCHASE = "IPG OTT PURCHASE";
  public static final String IPG_PURCHASE = "IPG PURCHASE";
  public static final String IPG_QUERY = "IPG QUERY";
  public static final String IPG_REFUND = "IPG REFUND";
  public static final String IPG_RESPONSE_SUCCESS = "0";
  public static final String IPG_TOKEN_LIST = "IPG TOKEN LIST";
  public static final String IPG_TOKEN_REMOVE = "IPG TOKEN REMOVE";
  public static final String IPG_TOKEN_STORE = "IPG TOKEN STORE";
  public static final String IPG_VOID_CAPTURE = "IPG VOID CAPTURE";
  public static final String IPG_VOID_PURCHASE = "IPG VOID PURCHASE";
  public static final String JSESSIONID_KEY = "JSESSIONID";
  public static final String KTS_DELETE = "KTS DELETE";
  public static final String KTS_DEL_TOKEN_FAILED = "Delete KTS Token Failed";
  public static final String KTS_DEL_TOKEN_SUCCESS = "Delete KTS Token Success";
  public static final String KTS_REG_FAILED = "KTS Registration Failed";
  public static final String KTS_REG_SUCCESS = "KTS Registration Success";
  public static final String KTS_RETRIEVE = "KTS RETRIEVE";
  public static final String KTS_RETRIEVE_FAILED = "KTS Retrieve Failed";
  public static final String KTS_RETRIEVE_SUCCESS = "KTS Retrieve Success";
  public static final String KTS_TOKENIZE = "KTS TOKENIZE";
  public static final String KTS_TOKENIZE_FAILED = "KTS Tokenization Failed";
  public static final String KTS_TOKENIZE_SUCCESS = "KTS Tokenization Success";
  public static final String LINK_CARD = "LINK CARD";
  public static final String LINK_FAILED = "Link Card Failed";
  public static final String LINK_SUCCESS = "Link Card Success";
  public static final String LOGIN_ADV_PATH = "/login/adv";
  public static final String LOGIN_APP = "LOGIN APPLICATION";
  public static final String LOGIN_PATH = "/login";
  public static final String LOGIN_SUCCESS = "Login Success";
  public static final String LOGIN_USER = "LOGIN USER";
  public static final String LOGOUT_FAILED = "Logout Failed";
  public static final String LOGOUT_PATH = "/logout";
  public static final String LOGOUT_SUCCESS = "Logout Success";
  public static final String LOGOUT_USER = "LOGOUT USER";
  public static final String LOG_TYPE_ERROR = "Error";
  public static final String LOG_TYPE_INFO = "Info";
  public static final String LOG_VERBOSITY_ALL = "All";
  public static final String LOG_VERBOSITY_ERROR = "Error";
  public static final String LOG_VERBOSITY_INFO = "Info";
  public static final String LOYALTY_CANCEL = "CANCEL";
  public static final String LOYALTY_INQUIRY = "INQUIRY";
  public static final String LOYALTY_ISSUE = "ISSUE";
  public static final String LOYALTY_REDEEM = "REDEEM";
  public static final String LOYALTY_REVERSE = "REVERSE";
  public static final String LOYALTY_SALES = "SALES";
  public static final String LOYALTY_VALIDATE = "VALIDATE";
  public static final String MERCHANT_PATH = "/merchant";
  public static final String MESSAGE_KEY = "message";
  public static final String NAME_KEY = "name";
  public static final String NEWPASSWORD = "newPassword";
  public static final String OWNER_KEY = "owner";
  public static final String PAN = "pan";
  public static final String PASSWORD = "password";
  public static final String POINT_PURCHASE_HISTORY = "POINT PURCHASE HISTORY";
  public static final String PREPAID_CREDENTIAL_KEY = "PREPAID_CREDENTIAL";
  public static final String PREPAID_GENERIC = "PREPAID";
  public static final String PREPAID_SERVER_NOT_RESPONSE = "Prepaid Server Not Response";
  public static final String PREPAID_SERVER_REQUEST = "PREPAID-SERVER";
  public static final String PREPAID_USER_REQUEST = "PREPAID-USER";
  public static final String PRINTED_NUMBER = "printedNumber";
  public static final String PRINT_NUMBER_KEY = "printNumber";
  public static final String PROMO_PATH = "/promo";
  public static final String PROPERTY_CARD_LINK_ID = "cardLinkId";
  public static final String PROPERTY_EMAIL = "email";
  public static final String PROPERTY_FULLNAME = "fullname";
  public static final String PROPERTY_NAME = "name";
  public static final String PROPERTY_PHONE_NUMBER = "phoneNumber";
  public static final String PROPERTY_PIN = "pin";
  public static final String REGISTER_USER = "REGISTER USER";
  public static final String RELOGIN_APP = "RELOGIN APPLICATION";
  public static final String REMOVE_USER_DEVICE_IMPRINTS = "REMOVE USER DEVICE IMPRINTS";
  public static final String REPASSWORD = "rePassword";
  public static final String REQUEST_TYPE = "REQUEST-TYPE=ENC";
  public static final String RESET_USER_DEVICE_IMPRINTS = "RESET ALL REGISTERED USER DEVICE IMPRINTS";
  public static final String RESPONSE_KEY = "response";
  public static final String SALE_COUPON = "SALE COUPON";
  public static final String SALE_LOYALTY = "LOYALTY SALE";
  public static final String SALE_POINT = "SALE POINT";
  public static final String SALE_PREPAID = "SALE PREPAID";
  public static final String SAVE_USER_CONFIG = "SAVE USER CONFIG";
  public static final String SAVE_USER_DEVICE_IMPRINTS = "SAVE USER DEVICE IMPRINTS";
  public static final String SECRET_KEY = "IPG-SECRET-KEY";
  public static final String SEND_EMAIL_USER = "SEND EMAIL TO USER";
  public static final String SERVER_NOT_RESPONSE = "Server Unable to Response";
  public static final String STATUS_CODE_FAILED_FIND = "41";
  public static final String STATUS_CODE_KEY = "statusCode";
  public static final String STATUS_CODE_SUCCESS = "200";
  public static final String STATUS_KEY = "status";
  public static final String STORE_COUPON = "STORE COUPON";
  public static final String STORE_CREDIT = "STORE CREDIT";
  public static final String STORE_POINT = "STORE POINT";
  public static final String SUCCESS = "Success";
  public static final String SUCCESS_ADD_CONFIG = "Add Config Success";
  public static final String SUCCESS_CONFIG_FOUND = "Found User Config";
  public static final Long SUCCESS_INDEX;
  public static final String SUCCESS_SEND_NOTIFICATION = "Notification successfully sended";
  public static final String SUCCESS_STATUS_IPG = "0";
  public static final String SUCCESS_STATUS_PREPAID = "00";
  public static final String SUCCESS_STATUS_PREPAID_CARD_EXIST = "20";
  public static final String SUCCESS_UPDATE_CONFIG = "Update Config Success";
  public static final String SWAGGER_PATH = "/api-docs";
  public static final String SWAGGER_UI_PATH = "/swagger-ui.html";
  public static final String TOP_UP_PREPAID = "TOP UP PREPAID";
  public static final String TOTAL_COUNT_KEY = "Total-Count";
  public static final String TOTAL_PAGE_KEY = "Total-Page";
  public static final String TOTAL_RECORDS_KEY = "totalRecords";
  public static final String UID_KEY = "UID";
  public static final String UNLINK_CARD = "UNLINK CARD";
  public static final String UNLINK_FAILED = "Unlink Card Failed";
  public static final String UNLINK_SUCCESS = "Unlink Card Success";
  public static final String UPDATE_SUCCESS = "Update Success";
  public static final String UPDATE_USER = "UPDATE USER";
  public static final String USERNAME_EXIST = "Username/Email Already Registered";
  public static final String USER_ADD_PATH = "/user/add";
  public static final String USER_CONTEXT_PATH = "/user/context/";
  public static final String USER_NOT_FOUND = "User Not Found";
  public static final String USER_PATH = "/user";
  public static final String VALIDATE_CARDLINK_UID = "VALIDATE CARDLINK UID";
  public static final String VALIDATION_AMOUNT = "5000";
  public static final String VALIDATION_COUPON_OWNER = "VALIDATE COUPON OWNER";
  public static final String VALUE_KEY = "value";
  public static final String VOID_COUPON = "VOID COUPON";
  public static final String VOID_CREDIT = "VOID CREDIT";
  public static final String VOID_POINT = "VOID POINT";
  public static final String VOID_PURCHASE = "VOID PURCHASE";
  public static final String WRONG_CC_TOKEN = "Unable to Untoken Creditcard";
  public static final String WRONG_PREPAID_TOKEN = "Unable to Untoken Giftcard";
  
  static
  {
    DISABLE = Integer.valueOf(0);
    DELETED = Integer.valueOf(0);
    ERROR_INDEX = Long.valueOf(1L);
    SUCCESS_INDEX = Long.valueOf(0L);
    GENERIC_SERVICE_IAM = Integer.valueOf(1);
    GENERIC_SERVICE_CARDLINK = Integer.valueOf(2);
    GENERIC_SERVICE_PROMO = Integer.valueOf(3);
  }
}


/* Location:              /Users/michael/Downloads/dex2jar-2.0/GO_JEK.jar!/com/kartuku/digitalwallet/common/Constants.class
 * Java compiler version: 6 (50.0)
 * JD-Core Version:       0.7.1
 */